# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='\u0438\u043c\u044f')),
                ('surname', models.CharField(max_length=120, verbose_name='\u0444\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('middle_name', models.CharField(max_length=120, verbose_name='\u043e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('date_of_birth', models.DateField(verbose_name='\u0434\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('email', models.EmailField(max_length=254, verbose_name='\u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0430\u044f \u043f\u043e\u0447\u0442\u0430')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='\u0442\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('beginning_of_work', models.DateField(verbose_name='\u043d\u0430\u0447\u0430\u043b\u043e \u0440\u0430\u0431\u043e\u0442\u044b')),
                ('end_of_work', models.DateField(blank=True, null=True, verbose_name='\u0437\u0430\u0432\u0435\u0440\u0435\u0448\u0435\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0442\u044b')),
                ('position', models.CharField(max_length=100, verbose_name='\u0434\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('department', models.CharField(max_length=100, verbose_name='\u043e\u0442\u0434\u0435\u043b')),
            ],
        ),
    ]
